

const collegeOfEducation = [
    "Federal College of Education (Technical), Asaba",
    "Federal College of Education, Kano",
    "Federal College of Education (Special), Oyo",
    "College of Education, Gindiri",
    "College of Education, Hong",
    "Tai Solarin College of Education, Ijebu-Ode",
    "College of Education, Ikere-Ekiti",
    "Ebonyi State College of Education, (T) Ikwo",
    "College of Education, Warri",
    "FCT College of Education, Zuba",
    "Delar College of Education",
    "Federal College of Education, Abeokuta",
    "Federal College of Education, Eha-Amufu",
    "Federal College of Education (Technical), Gombe",
    "Federal College of Education, Kontagora",
    "Federal College of Education, Okene",
    "Federal College of Education (Technical), Omoku",
    "Federal College of Education (Tech), Potiskum",
    "Nasarrawa State College of Education, Akwanga",
    "Isa Kaita College of Education, Dutsin-Ma",
    "College of Education, Ekiadolor-Benin",
    "College of Education, Gashua, Damaturu",
    "Kaduna State College of Education, Gidan-Waya, Kafanchan",
    "Osun State College of Education, Ilesa",
    "College of Education Oro",
    "College of Education, katsina-Ala",
    "Sa`adatu Rimi College of Education, Kumbotso, Kano",
    "College of Education (Technical), Lafiagi",
    "Nwafor Orizu College of Education, Nsugbe",
    "Adeniran Ogunsanya College of Education, Otto/Ijanikin",
    "Alvan Ikoku College of Education, Owerri",
    "Emmanuel Alayande College of Education (EACOED), Oyo",
    "College of Education, Waka BIU",
    "City College of Education, Mararaba",
    "Federal College of Education (Technical), Akoka",
    "Federal College of Education (Technical), Bichi",
    "Federal College of Education (Technical), Gusau",
    "Federal College of Education, Katsina",
    "Federal College of Education, Obudu",
    "Adeyemi College of Education, Ondo",
    "Federal College of Education, Pankshin",
    "Federal College of Education, Yola",
    "Delta State College of Education, Agbor",
    "Federal College of Education, Zaria",
    "Akwa Ibom State College of Education, Afahansit",
    "Kogi State College of Education, Ankpa",
    "Adamu Augie College of Education, Argungu",
    "Aminu Sale College of Education, Azare",
    "Umar Ibn Ibrahim El-Kanemi College of Education, Science and Technology, Bama",
    "Nigerian Army School of Education (NASE), Ilorin",
    "Zamfara State College of Education, Maru",
    "Jigawa State College of Education, Gumel",
    "Niger State College of Education, Minna",
    "Shehu Shagari College of Education, Sokoto",
    "Ansar-Ud-Deen College of Education, Isolo",
    "Yewa Central College of Education, Ayetoro, Abeokuta",
    "Federal College of Education (T), Umunze",
    "College of Education, Arochukwu, Abia",
    "College of Education, Ila-Orangun, Osun State",
    "Michael Otedola Coll. of Prim. Education, Lagos",
    "Kashim Ibrahim College of Education",
    "Delta State Coll. of Physical Education, Mosogar",
    "Enugu State Coll. of Education (T), Enugu",
    "Cross River State Coll. of Education, Akampa",
    "Edo State College of Education, Igueben",
    "Isaac Jasper Boro COE, Sagbama",
    "Kogi State College of Education, Kabba",
    "Osisa Tech. College of Education, Enugu",
    "St. Augustine College of Education Akoka, Lagos",
    "African Thinkers Community of Inquiry COE, Enugu",
    "Muftau Olanihun College of Education, Ibadan",
    "Havard Wilson College of Education, Aba",
    "Muhyideen College of Education, Ilorin",
    "Corner Stone College of Education, Ikeja",
    "Peaceland College of Education, Enugu",
    "The College of Education, Nsukka",
    "Unity College of Education, Aukpa Adoka, Benue",
    "DIAMOND COLLEGE OF EDUCATION, ABA",
    "National Teachers Institute(NTI)",
    "Kingsey College of Education, Ilorin, Kwara State",
    "ECWA College of Education, Jos (ECOEJ)",
    "FESTMED COLLEGE OF EDUCATION, ONDO STATE",
    "BETHEL COE IJARE, ONDO",
    "STEADY FLOW COE, IKOM",
    "AL HIKMA COLLEGE OF EDUCATION, ANKPA",
    "Global COE, Bukuru",
    "Kwararafa COE, Otukpo",
    "College of Education, Billiri",
    "Lessel COE Gboko",
    "Bayo Tijani COE, Lagos",
    "Upland COE Badagry",
    "College of Education, Zing",
    "ECWA COE Igbaja",
    "PAN African COE Offa",
    "Corona COE Lekki",
    "College of Education Oju",
    "EEICOE Otukpo",
    "Sinai COE & Ent. Studies Gboko, Benue",
    "MCF COE Agbarha-Otor, Delta",
    "Assanusiya COE, Odeomu, Osun",
    "COE, Ero, Akure",
    "Calvin Foundation COE",
    "Best Legacy COE Ogbomoso",
    "Angel Crown COE",
    "Elder Oyama Memorial COE, Ofat",
    "COE, Moro, Ife-North",
    "Royal City COE, Iyesi-Ota",
    "ONIT COE, Abagana",
    "Nana Aishat Memorial COE",
    "Top-Most COE, Ipaja-Agbado",
    "Apa COE, Aido",
    "Awori District COE",
    "Hill COE, Gwanje, Akwanga",
    "Aminu Kano College of Education",
    "Murtadha COE, Olodo",
    "Islamic COE, Potiskum",
    "Royal COE, Ikeja, Lagos State",
    "Hassan Usman Katsina Polytechnic",
    "Plateau State Polytechnic",
    "Kano State Polytechnic",
    "Waziri Umaru Federal Polytechnic",
    "Ramat Polytechnic",
    "Kaduna Polytechnics",
    "Abubakar Tatari Polytechnic",
    "Nuhu Bamalli Polytechnic",
    "Ipere COE, Agyaragu",
    "Piaget College of Education",
    "Biga College of Education",
    "Al-Ibadan COE",
    "College of Education Kura",
    "Sunnah College of Education",
    "Oswald Waller COE Shendam",
    "Imam Saidu COE, Funtua",
    "Bilyaminu Othman COE Dass",
    "The Polytechnic Iree, Osun State",
    "Bogoro College of Education",
    "Adesina College of Education, Share, Kwara State",
    "Covenant College of Education (CCOE)",
    "JIGAWA STATE COLLEGE OF EDUCATION AND LEGAL STUDIES, RINGIM",
    "CRESTFIELD COLLEGE OF EDUCATION",
    "GRACE COLLEGE OF EDUCATION",
    "AFRICAN CHURCH COLLEGE OF EDUCATION",
    "Kano State College of Education and Remedial Studies, Kano",
    "College of Education, Lanlate, Oyo State",
    "Climax College of Education, Bauchi",
    "College of Education and Legal Studies",
    "Federal College of Education Sokoto",
    "Federal College of Education Bauchi",
    "Federal College of Education (T), ISU Ebonyi State",
    "Federal College of Education, Odugbo, Benue State",
    "Federal College of Education Osun",
    "Federal College of Education Edo",
    "Kashim Ibrahim College of Education",
    "College of Education Oro",
    "Imo State College of Education, Ihitte/Uboma",
    "Annur College of Education Kano",
    "College of Education Ilemona",
    "Ebenezer College of Education Amangwu",
    "JIBWIS College of Education Gombe",
    "Kogi East College of Education",
    "Gboko College of Education Benue State",
    "Hope and Anchor College of Education",
    "Elizabeth Memorial College of Education Nsukka",
    "Ilori College of Education , Ede",
    "Sarkin Yama Community College of Education",
    "Umar Bun Khatab College of Education, Tudun Nupawa, Kaduna",
    "Peacock College of Education Jalingo",
    "Peace College Of Education Ankpa",
    "Moje College of Education, Erin-Ile",
    "Uli College of Education, Uli",
    "Lifegate College of Education, Asa",
    "JIBWIS COE, Jamaare",
    "Dala College of Education, Kano",
    "Hamzainab College of Education, Oshogbo",
    "College of Education, Darazo",
    "Abubakar Garba Zagada- Zagada College of Education, Bajoga",
    "Imam Hamzat COE, Ilorin",
    "Metro COE, Adogi-Lafia",
    "College of Sharia and Arabic Studies",
    "Abdullahi Maikano College of Education, Wase",
    "Nosakhare COE, Benin City",
    "Good Shepperd COE",
    "Turath COE, Kano",
    "Meadow Hall COE",
    "Raphat COE",
    "Kazaure College of Education",
    "JIBWIS College of Education",
    "Adamu Garkuwa COE, Toro",
    "Folrac Fortified COE, Ondo",
    "Al-Iman College of Education",
    "Danyaya College of Education, Ningi",
    "Innovative College of Education, Karu",
    "Sam Ale College of Education",
    "Gombe State COE, NAFADA",
    "Gand-Plus College of Education",
    "Olekamba College of Education",
    "Emamo College of Education",
    "Aminu Kano College of Islamic and Legal Studies",
    "Muhammad Goni College of Legal and Islamic Studies (MOGOLIS)",
    "A.D. Rufai College for Islamic and Legal Studies",
    'Yusuf Bala Usman College of Legal and General Studies, Daura',
    "Bauchi Institute for Arabic and Islamic Studies",
    "Institute of Ecumenical Education (Thinkers Corner)",
    "Ameer Shehu Idris College of Advanced Studies, Zaria",
    "National Institute for Nigerian Languages (NINLAN)",
];

module.exports = collegeOfEducation;
