

const polytechnics = [
    "Air Force Institute of Technology, Kaduna, Kaduna State",
    "Federal Polytechnic, Auchi, Edo State",
    "Federal Polytechnic, Ado-Ekiti, Ekiti State",
    "Akanu Ibiam Federal Polytechnic, Unwana, Ebonyi State",
    "Federal Polytechnic, Bali, Taraba State",
    "Federal Polytechnic, Bauchi, Bauchi State",
    "Federal Polytechnic, Bida, Niger State",
    "Federal Polytechnic, Damaturu, Yobe State",
    "Federal Polytechnic, Ede, Osun State",
    "Federal Polytechnic, Ekowe, Bayelsa State",
    "Federal Polytechnic, Idah Kogi State",
    "Federal Polytechnic, Ilaro, Ogun State",
    "Federal Polytechnic, Mubi, Adamawa State",
    "Federal Polytechnic, Kaura/Namoda, Zamfara State",
    "Federal Polytechnic, Nasarawa, Nasarawa State",
    "Federal Polytechnic, Nekede, Owerri, Imo State",
    "Federal Polytechnic, Offa, Kwara State",
    "Federal Polytechnic, Oko, Orumba North L.G.A, Anambra State",
    "Federal Polytechnic, Ile-Oluji, Ondo State",
    "Federal Polytechnic, Ukana, Essien Udim, Akwa Ibom State",
    "Federal School of Dental Technology and Therapy, Enugu, Enugu State",
    "Kaduna Polytechnic, Kaduna, Kaduna State",
    "Hussaini Adamu Federal Polytechnic, Kazaure, Jigawa State",
    "Nigeria Army Institute of Technology and Environmental Studies, Makurdi, Benue State",
    "National Institute for Construction Technology, Uromi, Edo State",
    "Waziri Umaru Federal Polytechnic Birnin Kebbi, Kebbi State",
    "Yaba College of Technology, Yaba, Lagos State",
    "Abraham Adesanya Polytechnic, Ijebu-Igbo, Ogun State Nigeria",
    "Abia State Polytechnic, Aba, Abia State",
    "Abia State College of Health Sciences and Management Technology, Aba, Abia State",
    "Abdu Gusau Polytechnic, Talata-Mafara, Zamfara State",
    "Akwa-Ibom State Polytechnic, Ikot-Osurua, Ikot-Ekpene, Akwa-Ibom State",
    "Mai Idris Alooma Polytechnic, Geidam, Yobe State",
    "Akwa Ibom State College of Arts and Science Nung, Ukim, Akwa Ibom State",
    "Abubakar Tatari Ali Polytechnic, Bauchi, Bauchi State",
    "Benue State Polytechnic, Ugbokolo, Benue State",
    "Binyaminu Usman College of Agriculture, Hadejia, Jigawa State",
    "Bayelsa State College of Arts and Science, Elebele, Bayelsa State",
    "College of Administrative and Business Studies, Potiskum, Yobe State",
    "College of Health Sciences and Technology, Ijero-Ekiti, Ekiti State",
    "D. S. Adegbenro ICT Polytechnic, Itori, Ogun State",
    "Enugu State Polytechnic, Iwollo, Ezeagu LGA, Enugu State",
    "The Polytechnic, Ibadan, Oyo State",
    "Imo State Polytechnic, Umuagwo, Ohaji, Imo State Nigeria",
    "Institute of Management and Technology, Enugu, Enugu State",
    "Institute of Technology and Management, Ugep, Cross River State",
    "Jigawa State Polytechnic, Dutse Jigawa State",
    "Kano State Polytechnic, Kano, Kano State",
    "Hassan Usman Katsina Polytechnic, Katsina, Katsina State",
    "Kogi State Polytechnic, Lokoja, Kogi State",
    "College of Business and Management Studies, Konduga, Borno State",
    "Kwara State Polytechnic, Ilorin, Kwara State",
    "Lagos State Polytechnic, Ikorodu, Lagos State",
    "Moshood Abiola Polytechnic, Abeokuta, Ogun State",
    "Nasarawa State Polytechnic, Lafia,  Nasarawa State",
    "Nuhu Bamalli Polytechnic, Zaria, Kaduna State",
    "Delta State Polytechnic, Ogwashi-Uku, Delta State",
    "Ogun State Institute of Technology, (formerly Gateway ICT Polytechnic), Igbesa, Ogun State",
    "The Oke-Ogun Polytechnic, Saki, Oyo State",
    "Delta State Polytechnic, Otefe, Delta State",
    "Osun State Polytechnic, Iree, Osun State",
    "Osun State College of Tech, Esa-Oke, Osun State",
    "Delta State Polytechnic, Ozoro, Delta State",
    "Port Harcourt Polytechnic, Rumuola, River State",
    "Plateau State Polytechnic, Barkin-Ladi, Plateau State",
    "Adamawa State Polytechnic, Yola, Adamawa State",
    "Ramat Polytechnic, Maiduguri, Borno State",
    "Rivers State College of Health Science, Rumueme, River State",
    "Rufus Giwa Polytechnic, Owo, Ondo State",
    "Gateway ICT Polytechnic, Saapade, Ogun State",
    "Kenule Beeson Saro-Wiwa Polytechnic, Bori, Rivers State",
    "Taraba State Polytechnic, Suntai, Taraba State",
    "The Ibarapa Polytechnic, Eruwa, Oyo State",
    "Umar Ali Shinkafi Polytechnic, Farfaru, Sokoto State",
    "Edo State Institute of Technology and Management, Usen, Edo State",
    "Niger State Polytechnic, Zungeru, Niger State",
    "Ajayi Polytechnic, Ikere-Ekiti, Ekiti State",
    "Al-Hikma Polytechnic, Karu, Nasarawa State",
    "Allover Central Polytechnic, Ota, Ogun State",
    "Bolmor Polytechnic, Agodi, Ibadan, Oyo State",
    "Best Solution Polytechnic, Akure, Ondo State",
    "Calvary Polytechnic, Owo-Oyibo, Delta State",
    "Covenant Polytechnic, Aba, Abia State",
    "Crown Polytechnic, Odo Ado-Ekiti, Ekiti State",
    "College of Technology, Iresi, Boluwaduro L.G.A., Osun State",
    "Dorben Polytechnic, Bwari-Garam Road, Abuja FCT",
    "Eastern Polytechnic, Rumuokwurusi, Port Harcourt, Rivers State",
    "Fidei Polytechnic, Gboko, Benue State",
    "Gboko Polytechnic, Gboko, Benue State",
    "Global Polytechnic, Akure, Ondo State",
    "Grace Polytechnic, Surulere, Lagos State",
    "Heritage Polytechnic, Ikot Udota, Akwa Ibom State",
    "Ibadan City Polytechnic, Dugbe, Ibadan, Oyo State",
    "Igbajo Polytechnic, Igbajo, Osun State",
    "The Polytechnic, Igbo-Owu, Ilorin Kwara State",
    "The Polytechnic, Ile-Ife, Ile-Ife, Osun State",
    "Interlink Polytechnic, Ijebu-Jesa, Osun State",
    "Kalac Christal Polytechnic, Sango-Tedo, Lekki, Lagos State",
    "Kings Polytechnic, Ubiaja, Edo State",
    "Lagos City Polytechnic, Ikeja, Lagos State",
    "Lens Polytechnic,Offa, Kwara State",
    "Light House Polytechnic, Evbuobanosa, Edo State",
    "Marist Polytechnic, Umuchigbo-De Nike Emene, Enugu, Enugu State",
    "NACABS Polytechnic, Akwanga, Nasarawa State",
    "Nogak Polytechnic, Ikom, Cross River State",
    "Our Saviour Institute of Science and Technology (Poly) Enugu, Enugu State",
    "The Polytechnic, Imesi-Ile, Osun State",
    "The Polytechnic, Adoka, Benue State",
    "Prime Polytechnic, Jidda Bassa, Ajaokuta, Kogi State",
    "RONIK Polytechnic, Alimosho, Lagos State",
    "Shaka Polytechnic, Ogiso, Benin City, Edo State",
    "St. Mary Polytechnic, Kwamba, Suleja, Niger State",
    "Sure Foundation Polytechnic, Ikot Akai, Akwa Ibom State",
    "Temple-Gate Polytechnic, Osisioma, Abia State",
    "Tower Polytechnic, Ibadan, Oyo State",
    "Trinity Polytechnic, Ifa Arai, Uyo, Akwa Ibom State",
    "Uma Ukpai Polytechnic, Osaga Ohafia, Abia State",
    "Uyo City Polytechnic, Uyo, Akwa Ibom State",
    "Valley View Polytechnic, Ohafia, Abia State",
    "Wolex Polytechnic, Dopemu, Lagos State",
];

module.exports = polytechnics;